config/routes.rb
Doubtfire::Application.routes.draw do
  devise_for :users
  mount Api::Root => '/'
  get 'api/submission/unit/:id/portfolio', to: 'portfolio_downloads#index'
  get 'api/submission/unit/:id/task_definitions/:task_def_id/download_submissions', to: 'task_downloads#index'
  get 'api/submission/unit/:id/task_definitions/:task_def_id/student_pdfs', to: 'task_submission_pdfs#index'
  get 'api/units/:id/all_resources', to: 'lecture_resource_downloads#index'
#  get 'api/units/:id/all_resources', to: 'count_increment#index'
end

app/models/unit.rb
require 'csv'
require 'bcrypt'
require 'json'
require 'moss_ruby'
require 'csv_helper'
require 'grade_helper'

class Unit < ActiveRecord::Base
  include ApplicationHelper
  include FileHelper
  include LogHelper
  include MimeCheckHelpers
  include CsvHelper

  #
  # Permissions around unit data
  #
  def self.permissions
    # What can students do with units?
    student_role_permissions = [
      :get_unit
    ]
    # What can tutors do with units?
    tutor_role_permissions = [
      :get_unit,
      :get_students,
      :enrol_student,
      :provide_feedback,
      :download_stats,
      :download_unit_csv,
      :download_grades
    ]

    # What can convenors do with units?
    convenor_role_permissions = [
      :get_unit,
      :get_students,
      :enrol_student,
      :upload_csv,
      :download_unit_csv,
      :update,
      :employ_staff,
      :add_tutorial,
      :add_task_def,
      :provide_feedback,
      :change_project_enrolment,
      :download_stats,
      :download_grades,
      :rollover_unit
    ]

    # What can admin do with units?
    admin_role_permissions = [
      :get_unit,
      :get_students,
      :enrol_student,
      :upload_csv,
      :rollover_unit,
      :change_project_enrolment,
      :update,
      :employ_staff,
      :add_tutorial,
      :add_task_def,
      :download_stats,
      :download_unit_csv,
      :download_grades,
    ]

    # What can other users do with units?
    nil_role_permissions = [

    ]

    # Return permissions hash
    {
      student: student_role_permissions,
      tutor: tutor_role_permissions,
      convenor: convenor_role_permissions,
      admin: admin_role_permissions,
      nil: nil_role_permissions
    }
  end

  def role_for(user)
    if convenors.where('unit_roles.user_id=:id', id: user.id).count == 1
      Role.convenor
    elsif tutors.where('unit_roles.user_id=:id', id: user.id).count == 1
      Role.tutor
    elsif active_projects.where('projects.user_id=:id', id: user.id).count == 1
      Role.student
    elsif user.has_admin_capability?
      Role.admin
    else
      nil
    end
  end

  # Ensure before destroy is above relations - as this needs to clear main convenor before unit roles are deleted
  before_destroy do
    update(main_convenor_id: nil)
    delete_associated_files
  end

  # Model associations.
  # When a Unit is destroyed, any TaskDefinitions, Tutorials, and ProjectConvenor instances will also be destroyed.
  has_many :tutorials, dependent: :destroy
  has_many :tutorial_enrolments, through: :tutorials
  has_many :tutorial_streams, dependent: :destroy
  has_many :task_definitions, -> { order 'start_date ASC, abbreviation ASC' }, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :unit_roles, dependent: :destroy
  has_many :teaching_staff, through: :unit_roles, class_name: 'User', source: 'user'
  has_many :learning_outcomes, dependent: :destroy
  has_many :tasks, through: :projects
  has_many :group_sets, dependent: :destroy
  has_many :task_engagements, through: :projects
  has_many :comments, through: :projects
  has_many :groups, through: :group_sets

  has_many :learning_outcome_task_links, through: :task_definitions

  has_many :convenors, -> { joins(:role).where('roles.name = :role', role: 'Convenor') }, class_name: 'UnitRole'
  has_many :staff, ->     { joins(:role).where('roles.name = :role_convenor or roles.name = :role_tutor', role_convenor: 'Convenor', role_tutor: 'Tutor') }, class_name: 'UnitRole'

  # Unit has a teaching period
  belongs_to :teaching_period

  belongs_to :main_convenor, class_name: 'UnitRole'

  validates :name, :description, :start_date, :end_date, presence: true

  validates :description, length: { maximum: 4095, allow_blank: true }

  validates :start_date, presence: true
  validates :end_date, presence: true

  validates :code, uniqueness: { scope: :teaching_period, message: "%{value} already exists in this teaching period" }, if: :has_teaching_period?

  validate :validate_end_date_after_start_date
  validate :ensure_teaching_period_dates_match, if: :has_teaching_period?

  validate :ensure_main_convenor_is_appropriate

  scope :current,               -> { current_for_date(Time.zone.now) }
  scope :current_for_date,      ->(date) { where('start_date <= ? AND end_date >= ?', date, date) }
  scope :not_current,           -> { not_current_for_date(Time.zone.now) }
  scope :not_current_for_date,  ->(date) { where('start_date > ? OR end_date < ?', date, date) }
  scope :set_active,            -> { where('active = ?', true) }
  scope :set_inactive,          -> { where('active = ?', false) }

  def add_tutorial_stream(name, abbreviation, activity_type)
    tutorial_stream = TutorialStream.new
    tutorial_stream.name = name
    tutorial_stream.abbreviation = abbreviation
    tutorial_stream.unit = self
    tutorial_stream.activity_type = activity_type
    tutorial_stream.save!

    # add after save to ensure valid tutorial stream
    self.tutorial_streams << tutorial_stream

    tutorial_stream
  end

  def update_tutorial_stream(existing_tutorial_stream, name, abbreviation, activity_type)
    existing_tutorial_stream.name = name if name.present?
    existing_tutorial_stream.abbreviation = abbreviation if abbreviation.present?
    existing_tutorial_stream.activity_type = activity_type if activity_type.present?
    existing_tutorial_stream.save!
    existing_tutorial_stream
  end

  def teaching_period_id=(tp_id)
    self.teaching_period = TeachingPeriod.find(tp_id)
    super(tp_id)
  end

  def teaching_period=(tp)
    if tp.present?
      write_attribute(:start_date, tp.start_date)
      write_attribute(:end_date, tp.end_date)
      write_attribute(:teaching_period_id, tp.id)
    end
    super(tp)
  end

  def has_teaching_period?
    self.teaching_period.present?
  end

  def ensure_teaching_period_dates_match
    if read_attribute(:start_date) != teaching_period.start_date
      errors.add(:start_date, "should match teaching period date")
    end
    if read_attribute(:end_date) != teaching_period.end_date
      errors.add(:end_date, "should match teaching period date")
    end
  end

  def ensure_main_convenor_is_appropriate
    return if main_convenor_id.nil?

    errors.add(:main_convenor, "must be a staff member from unit") unless id == main_convenor.unit_id
    errors.add(:main_convenor, "must be configured to administer unit") unless main_convenor.is_convenor?
    errors.add(:main_convenor, "must be capable of administering units - ensure user has appropriate permissions (contact admin staff to update)") unless main_convenor_user.has_convenor_capability?
  end

  def validate_end_date_after_start_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, "should be after the Start date")
    end
  end

  def rollover(teaching_period, start_date, end_date)
    new_unit = self.dup

    if teaching_period.present?
      new_unit.teaching_period = teaching_period
    else
      new_unit.start_date = start_date
      new_unit.end_date = end_date
    end

    # Clear main convenor - do not use old role id
    new_unit.main_convenor_id = nil

    new_unit.save!

    # Only employ the main convenor... they can add additional staff
    new_unit.employ_staff main_convenor_user, Role.convenor

    # Duplicate tutorial streams
    tutorial_streams.each do |tutorial_stream|
      new_unit.tutorial_streams << tutorial_stream.dup
    end

    # Duplicate group sets - before tasks as some tasks are group tasks
    group_sets.each do |group_set|
      new_unit.group_sets << group_set.dup
    end

    # Duplicate task definitions
    task_definitions.each do |td|
      td.copy_to(new_unit)
    end

    # Duplicate unit learning outcomes
    learning_outcomes.each do |learning_outcome|
      new_unit.learning_outcomes << learning_outcome.dup
    end

    # Duplicate alignments
    task_outcome_alignments.each do |align|
      align.duplicate_to(new_unit)
    end

    new_unit
  end

  def ordered_ilos
    learning_outcomes.order(:ilo_number)
  end

  def task_outcome_alignments
    learning_outcome_task_links.where('task_id is NULL')
  end

  def student_tasks
    tasks.joins(:task_definition).where('projects.enrolled = TRUE')
  end

  def self.for_user_admin(user)
    if user.has_admin_capability?
      Unit.all
    else
      Unit.joins(:unit_roles).where('unit_roles.user_id = :user_id and unit_roles.role_id = :convenor_role', user_id: user.id, convenor_role: Role.convenor.id)
    end
  end

  def self.default
    unit = new

    unit.name         = 'New Unit'
    unit.description  = 'Enter a description for this unit.'
    unit.start_date   = Date.today
    unit.end_date     = 13.weeks.from_now

    unit
  end

  #
  # Returns the tutors associated with this Unit
  # - includes convenor
  def tutors
    User.teaching(self)
  end

  def main_convenor_user
    main_convenor.user
  end

  def students
    projects
  end

  def student_query(limit_to_enrolled)
    # Get the number of tasks for each grade... with 1 as minimum to avoid / 0
    task_count = [0, 1, 2, 3].map do |e|
      task_definitions.where("target_grade <= #{e}").count + 0.0
    end.map { |e| e == 0 ? 1 : e }

    q = projects
        .joins(:user)
        .joins('LEFT OUTER JOIN tasks ON projects.id = tasks.project_id')
        .joins('LEFT JOIN task_definitions ON tasks.task_definition_id = task_definitions.id')
        .joins('LEFT OUTER JOIN plagiarism_match_links ON tasks.id = plagiarism_match_links.task_id')
        .joins('LEFT OUTER JOIN tutorial_enrolments ON tutorial_enrolments.project_id = projects.id')
        .joins('LEFT OUTER JOIN tutorials ON tutorials.id = tutorial_enrolments.tutorial_id')
        .joins('LEFT OUTER JOIN tutorial_streams ON tutorial_enrolments.tutorial_stream_id = tutorial_streams.id')
        .group(
          'projects.id',
          'projects.target_grade',
          'projects.enrolled',
          'users.first_name',

app/views/units/_summary_information.html.erb
<div class="widget-header">
    <h2><i class="icon-book"></i>Summary</h2>
</div>
<div class="widget-content">
    <dl class="dl-horizontal">
        <dt><strong><%= Unit.human_attribute_name(:name) %>:</strong></dt>
        <dd><%= unit.name %></dd>
        <dt><strong><%= Unit.human_attribute_name(:description) %>:</strong></dt>
        <dd><%= unit.description %></dd>
        <dt><strong><%= Unit.human_attribute_name(:start_date) %>:</strong></dt>
        <dd><%= unit.start_date.strftime("%d %B %Y") %></dd>
        <dt><strong><%= Unit.human_attribute_name(:end_date) %>:</strong></dt>
        <dd><%= unit.end_date.strftime("%d %B %Y") %></dd>
    </dl>
    <hr />
    <%= link_to t('.edit', default:  t("helpers.links.edit")), edit_unit_path(unit), class:  'btn' %>
</div>

app/views/units/_table.html.erb
<p id="no-units-message" <%= "hidden='hidden'" if not units.empty? %> ><%= empty_table_string %></p>
<table id="units-table" class="table table-striped" <%= "hidden='hidden'" if units.empty? %> <%= empty_table_string %>>
  <thead>
    <tr>
      <th><%= Unit.human_attribute_name(:name) %></th>
      <th><%= Unit.human_attribute_name(:description) %></th>
      <th>Convenors</th>
      <th><%= Unit.human_attribute_name(:start_date) %></th>
      <th><%= Unit.human_attribute_name(:end_date) %></th>
      <th><%= Unit.human_attribute_name(:active) %></th>
      <th><%=t '.actions', default:  t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% units.each do |unit| %>
      <%= render partial: '/units/table_row', locals: {unit: unit} %>
    <% end %>
  </tbody>
</table>

app/views/units/_table_row.html.erb
<tr id="project-<%= unit.id %>-row">
  <td><%= link_to unit.name, unit_path(unit) %></td>
  <td><%= unit.description %></td>
  <td><%= get_convenors_string(unit.id) %></td>
  <td><%= unit.start_date.strftime("%d %B %Y") %></td>
  <td><%= unit.end_date.strftime("%d %B %Y") %></td>
  <td><%= unit.active ? "Yes" : "No" %></td>
  <td>
    <%= link_to t('.edit', default:  t("helpers.links.edit")),
                edit_unit_path(unit), 
                "data-remote" => true,
                class:  'btn btn-mini' %>
    <%= link_to t('.destroy', default:  t("helpers.links.destroy")),
                unit_path(unit),
                "data-remote" => true,
                method:  :delete,
                data:  { confirm:  t('.confirm', default:  t("helpers.links.confirm", default:  'Are you sure?'))},
                class:  'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/units/edit.html.erb
<%- model_class = @unit.class -%>
<div class="page-header">
  <h1><%=t '.title', default:  t('helpers.titles.edit', model:  model_class.model_name.human,
                                   default:  "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render partial: 'form', locals: { unit: @unit } %>